(********************************************************************
 * COPYRIGHT -- General Atomics
 ********************************************************************
 * Program: AxisStateMachine
 * File: AxisStateMachineExit.st
 * Author: Administrator
 * Created: January 16, 2014
 ********************************************************************
 * Implementation of program AxisStateMachine
 ********************************************************************)

PROGRAM _EXIT


(* TODO : Add your code here *)


END_PROGRAM
